[build]
buildCommand = "npm run build"
nixpacksPlan = "nixpacks.toml"

[deploy]
startCommand = "timeout 30 npx prisma migrate deploy; npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

