-- CreateTable
CREATE TABLE "faqs" (
    "id" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'General',
    "questionEn" TEXT NOT NULL,
    "questionEs" TEXT NOT NULL,
    "answerEn" TEXT NOT NULL,
    "answerEs" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "faqs_pkey" PRIMARY KEY ("id")
);

-- Seed initial FAQ content (admins can edit/add/remove these afterward)
INSERT INTO "faqs" ("id","category","order","questionEn","questionEs","answerEn","answerEs","updatedAt") VALUES
('faq_start_1','Getting Started',1,
 $$How do I create a new league?$$,
 $$¿Cómo creo una liga nueva?$$,
 $$From the landing page, click "Create your league" (or Register). Pick a plan, name your league, and you will be set up as its admin.$$,
 $$En la página principal, haz clic en "Crea tu liga" (o Regístrate). Elige un plan, nombra tu liga y quedarás como su administrador.$$,
 CURRENT_TIMESTAMP),
('faq_start_2','Getting Started',2,
 $$What can each role do?$$,
 $$¿Qué puede hacer cada rol?$$,
 $$League Admins set up seasons, teams and schedules. Team Managers manage their roster. Scorekeepers score games. Players see their team, schedule and stats.$$,
 $$Los administradores configuran temporadas, equipos y calendarios. Los managers gestionan su róster. Los anotadores registran los juegos. Los jugadores ven su equipo, calendario y estadísticas.$$,
 CURRENT_TIMESTAMP),
('faq_bill_1','Subscriptions & Billing',1,
 $$How does billing work?$$,
 $$¿Cómo funciona la facturación?$$,
 $$Each league runs on a yearly plan (Single, Double, Triple or Homerun). Plans differ by how many games you can run per year. You can upgrade anytime.$$,
 $$Cada liga tiene un plan anual (Single, Double, Triple o Homerun). Los planes se diferencian por cuántos juegos puedes registrar al año. Puedes mejorar tu plan cuando quieras.$$,
 CURRENT_TIMESTAMP),
('faq_bill_2','Subscriptions & Billing',2,
 $$What happens when I reach my game limit?$$,
 $$¿Qué pasa si llego al límite de juegos?$$,
 $$You will see a prompt to upgrade or renew. Your existing data stays; you simply cannot schedule new games until you upgrade or the billing period renews.$$,
 $$Verás un aviso para mejorar o renovar. Tus datos se conservan; solo no podrás programar juegos nuevos hasta mejorar el plan o renovar el periodo.$$,
 CURRENT_TIMESTAMP),
('faq_bill_3','Subscriptions & Billing',3,
 $$How do I manage or cancel my subscription?$$,
 $$¿Cómo gestiono o cancelo mi suscripción?$$,
 $$League admins can open the billing portal from the league dashboard to update payment details, change plan, or cancel.$$,
 $$Los administradores pueden abrir el portal de facturación desde el panel de la liga para actualizar el pago, cambiar de plan o cancelar.$$,
 CURRENT_TIMESTAMP),
('faq_roster_1','Roster & Players',1,
 $$How do I add a player to my team?$$,
 $$¿Cómo agrego un jugador a mi equipo?$$,
 $$As a Team Manager, open your league, go to Teams, show your roster, and click "+ Add player". See the "Managing your roster" tutorial above.$$,
 $$Como manager, abre tu liga, ve a Equipos, muestra tu róster y haz clic en "+ Agregar jugador". Mira el tutorial "Gestiona tu róster" de arriba.$$,
 CURRENT_TIMESTAMP),
('faq_roster_2','Roster & Players',2,
 $$How do I add a player photo?$$,
 $$¿Cómo agrego la foto de un jugador?$$,
 $$In your roster, click "Photo" next to a player, upload or take a photo, adjust the square crop, and save.$$,
 $$En tu róster, haz clic en "Foto" junto al jugador, sube o toma una foto, ajusta el recorte cuadrado y guarda.$$,
 CURRENT_TIMESTAMP),
('faq_roster_3','Roster & Players',3,
 $$Can players see their own stats?$$,
 $$¿Los jugadores pueden ver sus estadísticas?$$,
 $$Yes. Players linked to an account see their team, schedule and personal stats when they sign in.$$,
 $$Sí. Los jugadores vinculados a una cuenta ven su equipo, calendario y estadísticas personales al iniciar sesión.$$,
 CURRENT_TIMESTAMP),
('faq_score_1','Scoring',1,
 $$Who can score a game?$$,
 $$¿Quién puede anotar un juego?$$,
 $$A Scorekeeper assigned to the game (or a league admin) scores it from the game page. See the "Scoring a game" tutorial above.$$,
 $$El anotador asignado al juego (o un administrador) lo anota desde la página del juego. Mira el tutorial "Anota un juego" de arriba.$$,
 CURRENT_TIMESTAMP),
('faq_score_2','Scoring',2,
 $$Can I correct a game after submitting the score?$$,
 $$¿Puedo corregir un juego después de enviar el resultado?$$,
 $$Yes. A league admin can reopen or reschedule the game to adjust the result. Reach out to your admin if you need a change.$$,
 $$Sí. Un administrador puede reabrir o reprogramar el juego para ajustar el resultado. Contacta a tu administrador si necesitas un cambio.$$,
 CURRENT_TIMESTAMP),
('faq_acct_1','Account',1,
 $$How do I change my password?$$,
 $$¿Cómo cambio mi contraseña?$$,
 $$Click "Change password" in the header while signed in. If you signed up with Google, manage sign-in from your Google account.$$,
 $$Haz clic en "Cambiar contraseña" en el encabezado al iniciar sesión. Si te registraste con Google, gestiona el acceso desde tu cuenta de Google.$$,
 CURRENT_TIMESTAMP),
('faq_acct_2','Account',2,
 $$Can I use the app in Spanish?$$,
 $$¿Puedo usar la app en español?$$,
 $$Yes. Use the language selector in the header to switch between English and Spanish anytime.$$,
 $$Sí. Usa el selector de idioma en el encabezado para cambiar entre inglés y español cuando quieras.$$,
 CURRENT_TIMESTAMP);
